(docs): add docs for visual matchers
webdriverio/expect-webdriverio pull request #1409
Opened 2024-01-08 05:35 UTC by christian-bromann

Adding documentation for visual matchers.

See implementation in https://github.com/webdriverio/visual-testing/pull/141

2024-01-08 06:24 UTC, wswebcreation requested changes
Thanks, can you also refer to them in the Visual Docs?

2024-01-08 06:24 UTC, wswebcreation commented on docs/API.md
> +### toMatchScreenSnapshot
```suggestion
### toMatchFullPageSnapshot
```

2024-01-08 06:24 UTC, wswebcreation commented on docs/API.md
> +### toMatchScreenSnapshot
```suggestion
### toMatchTabbablePageSnapshot
```

2024-01-11 03:46 UTC, christian-bromann commented
Enhanced visual docs with custom visual matcher:
<img width="1812" alt="Screenshot 2024-01-10 at 7 44 29 PM" src="https://github.com/webdriverio/expect-webdriverio/assets/731337/c1d17518-933d-4342-9f1a-24bf5a20c349">

@wswebcreation is this good to go?

2024-01-11 06:52 UTC, wswebcreation approved these changes
LGTM, thanks

2024-01-11 06:53 UTC, merged