refactor: delete XXXContaining
webdriverio/expect-webdriverio pull request #1550
Opened 2024-05-18 01:11 UTC by goosewobbler

Closes https://github.com/webdriverio/expect-webdriverio/issues/1366

2024-05-18 15:38 UTC, christian-bromann requested changes

2024-05-18 15:38 UTC, christian-bromann commented on docs/API.md
> -await expect(myInput).toHaveAttribute('class', expect.stringContaining('form'))
Could we add this as example to the matchers so people see how they can assert against the full or partial text.

2024-05-22 16:11 UTC, christian-bromann approved these changes
👍 

I will keep this PR around until we are at the point where we release the first alpha v9 version.

2024-05-22 20:06 UTC, goosewobbler commented
There are also some references to the removed functions in the main WDIO repo, in `eslint-plugin-wdio`.

2024-05-22 20:18 UTC, christian-bromann commented
@goosewobbler good catch, we can remove them in `main`.

2024-06-20 01:21 UTC, merged