Fix not matchers
webdriverio/expect-webdriverio pull request #170
Opened 2020-08-30 11:05 UTC by mgrybyk

* revert changes in `utils.ts` related to `waitUntil` function logic introduced in https://github.com/webdriverio/expect-webdriverio/pull/133
* add tests for `not` matchers

fixes: https://github.com/webdriverio/expect-webdriverio/issues/168

2020-08-30 12:56 UTC, mgrybyk commented
let's increase coverage with https://github.com/webdriverio/expect-webdriverio/issues/169

2020-08-31 07:08 UTC, christian-bromann requested changes
I feel like some of the assertions should stay as is or I am confusing something.

2020-08-31 07:08 UTC, christian-bromann commented on test/matchers/mock/toBeCalled.test.ts
> +        expect(result.pass).toBe(false)
Shouldn't `expect(mock).not.toBeRequested()` pass here?

2020-08-31 07:08 UTC, christian-bromann commented on test/matchers/mock/toBeCalledTimes.test.ts
> +        expect(result.pass).toBe(true)
same here .. `expect(mock).not.toBeRequestedTimes(0)` should mean the mock was requested at least 1 time or more to pass but it was not requested so far which should make the assertion `expect(result.pass).toBe(false)` pass.

2020-08-31 11:16 UTC, mgrybyk commented
This is just the same confusion I've faced.

If isNot is true and result.pass is true - the assertion would fail.
In order assertion to succeed when this.isNot is true result.pass should be false.

I spent some time going crazy with all that, that's why Ive added so many tests

2020-08-31 11:18 UTC, mgrybyk commented
Please see how other matchers work, ex test/matchers/beMatchers.test.ts

2020-08-31 13:43 UTC, christian-bromann approved these changes
I see, yeah that is pretty confusing 😆

2020-08-31 13:50 UTC, mgrybyk commented
resolved the conflicts

2020-08-31 14:01 UTC, merged